### ISSUE TITLE
Logo app

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/esnbang#1]
Faire le logo de l'app

**Comment by Alystrasz** [comment]
Version actuelle du logo : 
![logo](https://user-images.githubusercontent.com/11993538/31124774-2e31ff78-a846-11e7-8304-81363dacbba6.png)

**Comment by mickahell** [comment]
Proposition la plus pertinente, mais problème choix des couleurs (cf @Alystrasz )
![big_bang_logo6](https://user-images.githubusercontent.com/20951376/34078785-613fd29e-e321-11e7-8a71-ed457208a749.png)

**Comment by Alystrasz** [comment]
On a pas besoin d'avoir les couleurs de l'étoile pour être corpos, c'est bien ça ?

**Comment by mickahell** [comment]
> On a pas besoin d'avoir les couleurs de l'étoile pour être corpos, c'est bien ça ?

Les 2 règles sont :
- Ou l'étoile est présente
- Ou 1 ou plusieurs couleurs officielles d'ESN sont présentes

Donc on peut très bien ne pas utiliser l'étoile **OU** on peut ne pas utiliser les couleurs d'ESN.
Après y'a différentes règles sur comment utiliser l'étoile et surtout sur comment ne pas l'utiliser
