### ISSUE TITLE
permettre de supprimer les onglets pré-établis

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/esnbang#13]
Tout est dans le titre, permettre de supprimer les onglets pré-établis

**Comment by mickahell** [comment]
Egalement necessaire pour WIndows, car éviterai d'avoir à re-télécharger l'apps si changement d'asso ou si déjà en bénévole "libre" (comité sans asso)

**Comment by mickahell** [comment]
Plus pouvoir en supprimer plusieurs en même temps sans avoir à refaire un clic droit pour faire apparaitre la croix

**Comment by Alystrasz** [comment]
Réglé avec le commit f0c4a97689252a8e63f0456998e24d84221bd83a
