### ISSUE TITLE
ajouter le maximum d'onglet en dur + favicone

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/esnbang#14]
Suite l'issue #15 
Ajouter le plus d'onglet en dur possible en donnant la possibilité de si pas de favicone donner, prendre celui du site par défaut.

**Comment by Alystrasz** [comment]
Tu entends quoi exactement par 

> Pas de favicon donné ?

L'énorme majorité des sites en possède un 😃

**Comment by mickahell** [comment]
> Pas de favicon donné ?

Genre tu sais sur ta version 3 on peut attribuer un favicone aux onglets par défaut, là du coup ce serait que si on n'attribue aps de favicone, que l'appli charge automatiquement celui du site par défaut.

**Comment by Alystrasz** [comment]
C'est déjà le comportement de l'application à vrai dire, l'application va forcément récupérer le favicon du site 😄

**Comment by Alystrasz** [comment]
Du coup, je peux fermer le ticket ?
