### ISSUE TITLE
Créer un installer

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/esnbang#16]
Ne plus avoir 150000 fcihiers avec l'exe

**Comment by Alystrasz** [comment]
La génération d'un installeur a été intégrée avec le commit d7fb20e90f53a81bd87afaac57a1756f6e886787
Il ne reste plus qu'à régler un petit souci de path sur les images du sélecteur de langage et l'installeur est 100% fonctionnel !  😃

**Comment by Alystrasz** [comment]
Fixé avec le commit 11fcfe32b78234d8e91bf71e9dea30b08ac713f4, je ferme l'issue !
