### ISSUE TITLE
Ajouter app

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/esnbang#2]
Mettre :

- PalloSpace
- BS
- MB
- Faucon d'or
- Slack/Mattermost
- ... (idées)

**Comment by Alystrasz** [comment]
**Fonctionne :** 
- Wiki ESN France
- BuddySystem (portail)(petit souci de présentation)

---

**Ne fonctionne pas (X-Frame-Options: SAMEORIGIN) :**
- PalloSpace
- ESN Live
- Framateam ("frame-ancestors 'self'")

**Comment by Alystrasz** [comment]
Problème résolu grâce au composant `webview` !
