### ISSUE TITLE
Orthographe Bannière

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/esnbang#20]
by **the** French G33k Team
Toujours majuscule aux adjectifs de nationalité et il faut un the devant

**Comment by Alystrasz** [comment]
Y'a plus qu'à demander à notre comité préféré :)

**Comment by mickahell** [comment]
Nan même pas besoin, y'a la modif dans la description ;)

**Comment by Alystrasz** [comment]
Si tu peux modifier le fichier, y'a pas de soucis ^^
