### ISSUE TITLE
Revient à l'onglet de base

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/esnbang#22]
Quand je suis sur un onglet et que je change de fenetre, et que je reviens sur Universe, l'app est remise sur l'onglet de départ (celle avce la bannière)

**Comment by Alystrasz** [comment]
Le changement d'onglet se fait à la fermeture de l'app, c'est fait afin d'avoir des notifications sur tous les onglets quand l'appli est fermée ; si un onglet focus reçoit du contenu alors que l'appli est fermée, il n'y aura pas de notification

**Comment by mickahell** [comment]
Ok, je vois le problème du coup ca veut dire que c'est un problème MAC. 
Je vois la modif de code à taper faut juste que je trouve où écrire ca

**Comment by Alystrasz** [comment]
Fixé avec le commit 1c1c3caf8b585eacc72d75063b2ea28d857858d2
