### ISSUE TITLE
Tuto démarrage

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/esnbang#25]
Le tuto ne démarre pas au démarrage

**Comment by Alystrasz** [comment]
Screens / vidéos ?

**Comment by Alystrasz** [comment]
Je n'arrive pas à résoudre le bug chez moi, je pense que c'est plutôt lié au fait que l'appli ne s'affiche pas toujours au lancement...

**Comment by Alystrasz** [comment]
Fixé avec 2ffdf2ba3374dcf20d180cc5c5564238cb26b465
