### ISSUE TITLE
Ajouter ++

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/esnbang#3]
Possibilité de mettre l'app que l'on veut par simple URL 
Exemple : 
<img width="67" alt="capture d ecran 2017-07-03 a 18 23 28" src="https://user-images.githubusercontent.com/20951376/27801161-cb59f070-601c-11e7-8de0-8aaddb7f5853.png">

**Comment by Alystrasz** [comment]
Ajout des fonctionnalités graphiques pour ajouter une nouvelle source d'informations, il ne reste plus qu'à implémenter "l'abonnement" concret :)

![1](https://user-images.githubusercontent.com/11993538/31124701-dc266052-a845-11e7-9bb6-920d9e7813b9.png)
![2](https://user-images.githubusercontent.com/11993538/31124705-e1193a94-a845-11e7-8ec7-d784236bc646.png)

**Comment by Alystrasz** [comment]
Fonctionnalité implémentée !
