### ISSUE TITLE
Pouvoir supprimer les onglets de base

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/esnbang#4]

**Comment by Alystrasz** [comment]
N'avions-nous pas dit que certains onglets de base étaient à laisser en toutes circonstances sur l'appli ?

**Comment by mickahell** [comment]
Si mais d'autre également à titre d'exemple, genre celui du module bénévole il faut que chacun puisse le modifier pour mettre le module qu'il souhaite.

**Comment by mickahell** [comment]
Les obligatoire pourraient être : 
- PalloSpace & Excel d'Or 
- A voir si d'autre

Et bien sur l'onglet home !

**Comment by Alystrasz** [comment]
Et pourquoi ne pas laisser chaque webmaster _créer_ sa propre version de l'application via un fichier texte qui contiendrait les onglets _de base_ ?

**Comment by mickahell** [comment]
Ce serait GRAAAAAAVE top

**Comment by mickahell** [comment]
Surtout que grace à ca, il serait possible d'avoir des versions personnalisable pour Prez/WPA/comcom/BC/licorne/...

**Comment by Alystrasz** [comment]
Je te laisse créer une nouvelle issue, du coup 👍
