### ISSUE TITLE
Editage d'url 

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/esnbang#5]
Avoir acces à l'URL afin de pouvoir revenir en arrière et un bouton retour

**Comment by Alystrasz** [comment]
Qu'est-ce que tu entends exactement par 

> revenir en arrière

?

**Comment by mickahell** [comment]
Genre 
<img width="418" alt="capture d ecran 2017-11-29 a 20 01 44" src="https://user-images.githubusercontent.com/20951376/33393686-40ae52ba-d540-11e7-8d04-4c177fcae9c7.png">

**Comment by Alystrasz** [comment]
Je sais pas, logiquement les pages que tu ajoutes à l'application n'ont pas besoin d'un bouton 'retour' pour accéder à toutes les fonctionnalités...
L'objectif de l'appli n'est pas de recoder un navigateur web ;)

**Comment by mickahell** [comment]
Je m'explique, j'ai l'onglet PS et je click sur le bouton ML et là je me retrouve bloqué à ne pas pouvoir retourner sur le PS, et je suis triste je déprime, je me suis suicide, ca mettrait ESN France dans la merde :P

**Comment by Alystrasz** [comment]
Pourquoi ne pas s'abonner à la fois au ML et au PS alors ? :+1:

**Comment by mickahell** [comment]
C'est le genre de page ou tu vas 1 fois tous les 32 du mois, après je comprend et partage ce que tu veux dire également

**Comment by Alystrasz** [comment]
Du coup, comment qu'on fait ?
- on drop l'édition d'URL...
- ... mais on intègre un bouton retour ?

Le tout pour la première release ?

**Comment by mickahell** [comment]
Je te propose un truc, on le lance sans ca et au file des utilisations et des feedbacks on verra. Qu'est ce que t'en penses ?

**Comment by Alystrasz** [comment]
Allez, c'est validé :)
