### ISSUE TITLE
Onglets ajoutés ne fonctionne pas

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/esnbang#6]
Les onglets ajouté ne fonctionne pas :
- Les favicon sont chargées mais pas le contenu de la page

**Comment by Alystrasz** [comment]
Je suis curieux de voir si les sites "de base" se chargent toujours, sachant qu'ils utilisent maintenant les mêmes méthodes que les sites ajoutés par l'utilisateur.
Tu as des messages d'erreur en console quand tu essayes d'afficher des sites ?

**Comment by mickahell** [comment]
Ne charge pas avant d'avoir crée une interaction telle qu'une actualisation de la page

**Comment by Alystrasz** [comment]
Il faudrait essayer de rafraîchir chaque page dès qu'elle est chargée avec un 
`frame.reloadIgnoringCache()` (https://electronjs.org/docs/api/webview-tag).
