### ISSUE TITLE
Connexion Galaxy oneshot

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/esnbang#8]
Avoir une connexion unique bloquant l'app, si absence de compte galaxy et permettant d'être connecté sur chaque platforme directement sans avoir à remettre ses identifiants

**Comment by Alystrasz** [comment]
J'ai besoin de quelqu'un connaissant le système d'authentification Galaxy, ou alors d'une documentation technique le concernant (ça marche avec des cookies ?).

**Comment by mickahell** [comment]
Le galaxy actuel fonctionne en cas, le prochain sera (normalement) avec oAuth2

**Comment by Alystrasz** [comment]
Je crois que tu peux archiver le projet @mickahell :smile:

**Comment by mickahell** [comment]
Beh nan, imagine quelqu'un veut l'utiliser 🙃
