### ISSUE TITLE
Application ne ferme jamais

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/esnbang#9]
L'app ne se ferme pas (même avec les commande habituels) et reste constamment en background avec constamment la notification :
<img width="377" alt="capture d ecran 2017-11-29 a 17 54 36" src="https://user-images.githubusercontent.com/20951376/33387796-82a3077c-d52e-11e7-9bdb-41b806a57afd.png">

**Comment by Alystrasz** [comment]
Essaie de virer la condition de plateforme sur l'appel `app.quit()`, au début du fichier `index.js` ?
